baseURL = '/'
languageCode = 'en-us'
title = 'New web site'

[menu]
[[menu.main]]
  identifier = 'car'
  name = 'car'
  pre = "pkw"
  url = '/car-tax-germany/'
  weight = 1

[[menu.main]]
  identifier = 'motorcycle'
  name = 'Motorcycle'
  pre = "motorrad"
  url = '/motorcycle-tax-germany/'
  weight = 2

[[menu.main]]
  identifier = 'RV'
  name = 'RV'
  pre = "wohnmobil"
  url = '/camper-tax-germany/'
  weight = 3

[[menu.main]]
  identifier = 'caravan'
  name = 'Caravan'
  pre = "wohnwagen"
  url = '/caravan-tax-germany/'
  weight = 4

[[menu.main]]
  identifier = 'truck'
  name = 'Truck'
  pre = "lkw"
  url = '/truck-tax-germany/'
  weight = 5

[[menu.main]]
  identifier = 'trailer'
  name = 'Trailer'
  pre = "anhaenger"
  url = '/trailer-tax-germany/'
  weight = 6

[[menu.main]]
  identifier = 'electric'
  name = 'Electric'
  pre = "efz"
  url = '/electric-vehicle-tax-germany/'
  weight = 7

[[menu.main]]
  identifier = 'oldtimer'
  name = 'Oldtimer'
  pre = "oldtimer"
  url = '/oldtimer-tax-germany/'
  weight = 8

[de]
[[menu.de]]
  identifier = 'pkw'
  name = 'Pkw'
  pre = "pkw"
  url = '/de/kfz-steuer-rechner/'
  weight = 1

[[menu.de]]
  identifier = 'motorrad'
  name = 'Motorrad'
  pre = "motorrad"
  url = '/de/motorrad-steuer-rechner/'
  weight = 2

[[menu.de]]
  identifier = 'wohnmobil'
  name = 'Wohnmobil'
  pre = "wohnmobil"
  url = '/de/wohnmobil-steuer-rechner/'
  weight = 3

[[menu.de]]
  identifier = 'wohnwagen'
  name = 'Wohnwagen'
  pre = "wohnwagen"
  url = '/de/wohnwagen-steuer-rechner/'
  weight = 4

[[menu.de]]
  identifier = 'lkw'
  name = 'Lkw'
  pre = "lkw"
  url = '/de/lkw-steuer-rechner/'
  weight = 5

[[menu.de]]
  identifier = 'anhaenger'
  name = 'Anhänger'
  pre = "anhaenger"
  url = '/de/anhaenger-steuer-rechner/'
  weight = 6

[[menu.de]]
  identifier = 'elektro'
  name = 'Elektro'
  pre = "efz"
  url = '/de/elektrofahrzeug-steuer-rechner/'
  weight = 7

[[menu.de]]
  identifier = 'oldtimer'
  name = 'Oldtimer'
  pre = "oldtimer"
  url = '/de/oldtimer-steuer-rechner/'
  weight = 8

[es]
[[menu.es]]
  identifier = 'vehículo'
  name = 'Vehículo'
  pre = "pkw"
  url = '/es/vehiculo-impuesto-alemania/'
  weight = 1

[[menu.es]]
  identifier = 'motocicleta'
  name = 'Motocicleta'
  pre = "motorrad"
  url = '/es/motocicleta-impuesto-alemania/'
  weight = 2

[[menu.es]]
  identifier = 'rv'
  name = 'RV'
  pre = "wohnmobil"
  url = '/es/rv-impuesto-alemania/'
  weight = 3

[[menu.es]]
  identifier = 'camión'
  name = 'Camión'
  pre = "lkw"
  url = '/es/camion-impuesto-alemania/'
  weight = 4

[[menu.es]]
  identifier = 'remolque'
  name = 'Remolque'
  pre = "anhaenger"
  url = '/es/remolque-impuesto-alemania/'
  weight = 5

[[menu.es]]
  identifier = 'eléctrico'
  name = 'Eléctrico'
  pre = "efz"
  url = '/es/electrico-vehiculo-impuesto-alemania/'
  weight = 7

[[menu.es]]
  identifier = 'antiguo'
  name = 'Antiguo'
  pre = "oldtimer"
  url = '/es/antiguo-impuesto-alemania/'
  weight = 8